//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Satwe_tool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Satwe_tool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V0.1
        ///
        ///1. 加入自动读取PKPM的工程项目目录，这样一般情况下，用户只需下拉列表即可查看工程信息
        ///2. 完善同步浏览功能，在同步模式下光标放到一边，拖动另外一边的滚动条，
        ///    将不进行同步滚动，这样方便工程师看两边内容行号不同的情况
        ///
        ///v0.2 
        ///1. 加入搜索功能
        ///2. 提供行号显示开关
        ///3. 提供详细，简约显示开关
        ///2. 初步设计关键指标
        ///
        ///v0.3
        ///1. 完成指标导航
        ///2. 加入刚度比
        ///3. 加入楼层承载力比
        ///4. 加入周期比
        ///
        ///V0.4
        ///1. 加入质量比
        ///2. 加入有效质量系数
        ///3. 加入剪重比
        ///4. 加入位移比和层间位移比
        ///
        ///V0.5
        ///1. 完成主要指标信息提取
        ///2. 完成主要指标信息的导航
        ///3. 初步设计指标Excel模板
        ///
        ///V0.6
        ///1. 加入一键导出Excel
        ///2. 完成承载力比，侧刚比，剪力，剪重比的图表功能
        ///
        ///V0.7
        ///1. 支持YJK，实现两个软件计算结果对比分析
        ///
        ///V0.7.1   
        ///1. 经过群里朋友的帮助测试，对个版本软件做了兼容性测试，绝大多数项目都能成功解析
        ///V0.7.2 
        ///1. 加入配置文 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpInfo {
            get {
                return ResourceManager.GetString("HelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	位移比：用于控制结构扭转效应，限制结构平面布置不规则性，避免产生过大的偏心而导致结构产生
        ///	        较大扭转效应。位移比也称为扭转位移比。指的是楼层最大弹性水平位移（或层间位移）与
        ///			楼层两端弹性水平位移（或层间位移）平均值的比值。
        ///	
        ///	计算要求：采用“规定水平力计算”考虑偶然偏心和刚性楼板假定，不考虑双向地震。
        ///
        ///	规范：《抗规》3.4.3、《高规》3.4.5条在考虑偶然偏心作用下相关限值：
        ///		  A级高度高层：不宜大于1.2；不应大于1.5
        ///		  B级高度高层：不宜大于1.2；不应大于1.4
        ///	
        ///	调整：位移比不满足说明结构刚心与形心偏心距过大。可利用程序的节点搜索功能在satwe的“分析
        ///		  结构图形和文本显示”中的“各层配筋构件编号简图”中快速找到位移最大的节点。加强该节
        ///		  点对应的墙柱等构件的刚度。也可找出位移最小的节点削弱其刚度。直到位移比满足要求。
        ///
        ///
        ///
        ///	关于平面扭转不规则
        ///		[多层：]
        ///		1.不考虑水平地震作用偶然偏心的多层：扭转位移比大于1.2→平面扭转不规则。
        ///
        ///		2.不考虑水平地震作用偶然偏心的多层：扭转位 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IndexDisp {
            get {
                return ResourceManager.GetString("IndexDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	位移角：控制结构的侧向刚度。位移角也称为层间位移角，指按弹性算法计算的楼层层间最大位移
        ///			与层高之比。制结构整体刚度和不规则性的主要指标。保证主体结构基本处于弹性受力状
        ///			态，避免混凝土受力构件出现裂缝或裂缝超过规范允许的范围。保证填充墙、管线等非结
        ///			构构件完好，避免出现明显损伤。
        ///
        ///	计算要求：不考虑偶然偏心，不考虑双向地震。
        ///
        ///	限值：高度不大于150m的按《高规》3.7.3条限定；高度不小于250m的不宜大于1/500。对于150和
        ///		  250之间的按线线插入法取用。《抗规》5.5.1
        ///.
        /// </summary>
        internal static string IndexDispAngle {
            get {
                return ResourceManager.GetString("IndexDispAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		
        ///	说明：刚重比用于控制结构的稳定性，避免结构在风荷载或地震作用下整体失稳。刚重比也是影响重力
        ///		  二阶效应的主要参数。刚重比指的就是结构侧向刚度与重力荷载的比值。刚重比不满足要求说明
        ///		  结构刚度相对于重力荷载过小，但刚重比过大，说明结构的经济技术指标太差，宜适当减小墙、
        ///		  柱等竖向构件的截面面积。《高规》5.4.1、5.4.4。结构抗倾覆验算和整体稳定验算在“结构设
        ///		  计信息”里查看。
        ///
        ///	调整：不满足时，只能通过人为调整改变结构布置，调整结构高宽比，加强墙柱等竖向构件的刚度。
        ///	
        ///	注意：刚重比对重力二阶效应的影响，刚重比过小时需要考虑重力二阶效应（程序提示），在SATWE参
        ///		  数设置中要考虑。
        ///
        ///
        ///
        ///    .
        /// </summary>
        internal static string IndexEg {
            get {
                return ResourceManager.GetString("IndexEg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	
        ///	说明：控制结构竖向不规则，根据刚度判断薄弱层，或者用于判断地下室结构刚度是否满足嵌固要求。
        ///	      楼层刚度不小于上一楼层侧向刚度的70%，或上三层平均值的80%。程序自动计算此楼层侧向刚度
        ///		  与上一楼层70%或80%上三层平均值的比值。Ratx1与Raty1比值大于1便可。薄弱层地震剪力放大
        ///		  系数为1.0说明没有薄弱层。
        ///	规范：《高规》3.5.2 、3.5.8—一般情况 ；《高规》5.3.7—地下室；《高规》10.2.3—转换层
        ///	
        ///	调整：程序会自动根据此比值识别薄弱层，且自动放大地震剪力1.25倍。放大地震剪力只会加强其承载
        ///	      力，并没有真正把薄弱层这个不利情况去除，所以还可以自行调整结构的竖向布置使结构在竖向
        ///		  刚度均匀。如可适当降低本层层高，加强本层墙柱梁的刚度。适当提高上部相关楼层的层高和削
        ///		  弱上部相关楼层墙柱梁的刚度。
        ///.
        /// </summary>
        internal static string IndexEi {
            get {
                return ResourceManager.GetString("IndexEi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	经济配筋率
        ///		梁：跨中1%~1.7%较经济，支座1.5%~2%较经济；梁端支座纵向受拉钢筋配筋率不大于2.5%，
        ///			当大于2%时需加大箍筋。
        ///
        ///		板的经济配筋率0.2%~0.4%较经济。
        ///
        ///		柱的经济配筋率1%~3%较经济。
        ///.
        /// </summary>
        internal static string IndexReinDesign {
            get {
                return ResourceManager.GetString("IndexReinDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	说明：控制结构竖向不规则，避免竖向楼层受剪承载力突变形成薄弱层，即本层受剪承载力与上一层
        ///		  受剪承载力之比。《抗规》3.4.3、《高规》3.5.3
        ///	
        ///	限值：A级高度不宜小于0.8，不应小于0.65；B级高度建筑不应小于0.75；薄弱层不小于上一层0.65。
        ///	
        ///	调整：程序自动计算承载力之比，但是没有自动判断是否超限，需人为识别判断。对于出现薄弱层时
        ///		  可以在SATWE调整信息中“指定薄弱层个数”中输入该层层号，将该楼层强制定义为薄弱层，S
        ///		  ATWE自动按《高规》3.5.8（强剪弱弯的思想）将该楼层地震剪力放大1.25倍。如果还需要人工
        ///		  调整，可适当提高本层构件强度（如增大配筋—柱箍筋、墙水平分布筋、提高混凝土强度、或
        ///		  加大截面）以提高本层墙、柱等抗侧力构件的承载力。或适当降低上部相关楼层墙、柱等抗侧
        ///		  力构件的承载力。
        ///.
        /// </summary>
        internal static string IndexRv {
            get {
                return ResourceManager.GetString("IndexRv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	说明：用于控制结构的扭转效应。周期比是第一扭转周期和第一平动周期的比值。《高规》3.4.5条。
        ///		  周期比不满足要求说明结构的抗扭刚度相对于侧移刚度过小，结构扭转效应大。周期比反应的
        ///		  是一种相对关系，也就是扭转和侧移的相对大小关系。而不是扭转效应的绝对值。所以说周期
        ///		  比不满足往往是结构构件布置不均匀导致整个结构刚度不均匀而使抗扭刚度过小。	限值：A
        ///		  级高度高层建筑不应大于0.9；B级高度高层建筑不应大于0.85。（A级B级《高规》3.3.1）
        ///	
        ///	调整：①人工进行调整。从公式Tt/T1可以看出有两种方法解决。一种是减小平面刚度，去除平面中部
        ///		  的部分剪力墙，使T1增大；一种是在平面周边增加剪力墙（根据材料力学扭转一章可以知道周
        ///		  边抗扭越好），提高抗扭刚度，降低Tt（根据周期公式可以知晓）。②第一或第二振型为扭转
        ///		  时：结构的第一第二振型宜为平动，扭转周期宜出现在第三周期及以后；程序中振型是根据周
        ///		  期的长短排序的，扭转周期出现在第一或第二位置时说明扭转周期过大→抗扭刚度过小。如果
        ///		  扭转周期出现在第一振型也就是出现在第一 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IndexTg {
            get {
                return ResourceManager.GetString("IndexTg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	说明：控制各楼层最小地震剪力，确保安全性，就像最小配筋率的要求，最小地震剪力达不到要求就
        ///	      需要人为提高。剪重比指的是结构任一层的水平地震剪力与该层及其以上各层总重力荷载代表
        ///		  值的比值。通常指底层水平剪力与结构总重力荷载代表值之比。剪重比在一定程度上反映了结
        ///		  构的刚柔程度。剪重比应在一个比较合理的范围内，以保证结构整体刚度适中。剪重比太小说
        ///		  明结构整体刚度偏柔，水平荷载或水平地震作用下将产生过大的水平位移或层间位移；剪重比
        ///		  过大说明结构整体刚度偏刚，会引起很大的地震力。
        ///	
        ///	限值：《抗规》5.2. 5、《高规》4.3.12 、3.3.13
        /// 
        ///	调整：程序自动将最小剪重比写入了文件中，用户自己把各剪重比与此最小剪重比进行比较即可。注
        ///		  意，要满足有效质量系数大于0.9。
        ///	
        ///	PKPM程序调整：SATWE调整信息中勾选按抗震规范5.25调整各楼层地震力；人为调整：①如果地震剪力
        ///		  偏小，层间侧移角偏大。说明结构过柔，需加大墙、柱截面提高刚度；②如果地震剪力偏大，层
        ///		  间侧移角偏小。说明结构过刚，需减小墙柱截面以降 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IndexVg {
            get {
                return ResourceManager.GetString("IndexVg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                               鸣谢！
        ///
        ///没有众多朋友的鼓励和支持，一个人的旅途是孤独的
        ///
        ///任何事情，没有朋友的帮助是难以做到极致的
        ///
        ///世间最美好的东西，莫过于有几个头脑和心地都很正直的严正的朋友
        ///
        ///感谢，我的朋友们，时间会流逝，白发会生长，但你们无私的奉献将积淀成深受广大工程师喜爱的工具
        ///感谢GICD QQ群（273211781）的朋友，以时间顺序：
        ///
        ///V1.0版本：
        ///1.  @住宅院-杨谦 提出同步按钮，同步切换tab页面
        ///2.  @包工头的令狐冲  无私奉献现有的助手工具供我参考
        ///3.  @HJ-Soyo 提供已有相关工具
        ///4.  @十二个魔法  帮解答专业问题
        ///5.  @合肥-钱   帮解答专业问题
        ///6.  @CSADI-舒  提供了指标分析Excel模板，帮解答专业问题
        ///7.  @黑夜/sun 提供专业指标分析PDF文档
        ///8.  @Helchan 提供了指标控制调整文档，自己写的喔，很专业
        ///
        ///
        ///感谢参与软件测试的所有网友，排名不分先后（可能还有被遗漏的无名英雄）：
        ///@影  youie2003@qq.com  @杜猛 @子弹丁@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThanksInfo {
            get {
                return ResourceManager.GetString("ThanksInfo", resourceCulture);
            }
        }
    }
}
